services:

  nginx:
    image: nginx:alpine
    container_name: ecosense_nginx

    ports:
      - "8080:80"

    volumes:
      - ./api:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - php

    networks:
      - ecosense_network


  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile

    container_name: ecosense_php

    volumes:
      - ./api:/var/www/html

    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}

    depends_on:
      - postgres

    networks:
      - ecosense_network


  postgres:
    image: postgres:17
    container_name: ecosense_postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - ecosense_network


  mosquitto:
    image: eclipse-mosquitto:2
    container_name: ecosense_mosquitto

    ports:
      - "1883:1883"

    volumes:
      - ./docker/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./docker/mosquitto/data:/mosquitto/data

    networks:
      - ecosense_network


volumes:
  postgres_data:


networks:
  ecosense_network:
    driver: bridge